[package]
name = "test-programs-http-get-activity"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
bitflags.workspace = true
wit-bindgen-rt.workspace = true

[lib]
crate-type = ["cdylib"]

[features]
wasm = []
default = ["wasm"]

[package.metadata.component.dependencies]

[package.metadata.component.target.dependencies]
"wasi:http" = { path = "wit/deps/http" }
"wasi:clocks" = { path = "wit/deps/clocks" }
"wasi:io" = { path = "wit/deps/io" }
"wasi:random" = { path = "wit/deps/random" }
"testing:http" = { path = "../wit" }
