[package]
name = "test-programs-http-get-activity"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
waki.workspace = true
wit-bindgen-rt.workspace = true

[lib]
crate-type = ["cdylib"]

[features]
wasm = []

[package.metadata.component.dependencies]

[package.metadata.component.target.dependencies]
"testing:http" = { path = "../wit" }
