[package]
name = "test-programs-sleep-activity-builder"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[build-dependencies]
cargo-component-builder.workspace = true
