[package]
name = "concepts"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true


[dependencies]
val-json.workspace = true

arbitrary.workspace = true
derive_more.workspace = true
getrandom.workspace = true      # Only needed for the madsim patch
serde_json.workspace = true
thiserror.workspace = true
ulid.workspace = true
wasmtime.workspace = true

[dev-dependencies]
insta.workspace = true
madsim.workspace = true

[lints]
workspace = true
