[package]
name = "concepts"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true


[dependencies]
val-json.workspace = true

arbitrary.workspace = true
cfg-if.workspace = true
derive_more.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing-unwrap.workspace = true
ulid.workspace = true
wasmtime.workspace = true

[dependencies-dev]
madsim.workspace = true

[lints]
workspace = true
