[package]
name = "workflow-cli"
version.workspace = true
authors.workspace = true
categories = ["wasm"]
keywords = ["webassembly", "wasm"]
readme = "README.md"
edition.workspace = true
rust-version.workspace = true

[dependencies]
runtime.workspace = true
val-json.workspace = true

anyhow.workspace = true
async-trait.workspace = true
lazy_static.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing-subscriber.workspace = true
wasmtime-wasi-http.workspace = true
wasmtime-wasi.workspace = true
wasmtime.workspace = true
wit-component.workspace = true
wit-parser.workspace = true

[workspace]
resolver = "2"
members = [
    "crates/runtime",
    "crates/testing/benches",
    "crates/testing/test-programs-builder",
    "crates/testing/test-programs/fibo/activity",
    "crates/testing/test-programs/fibo/workflow",
    "crates/testing/test-programs/http/activity",
    "crates/testing/test-programs/http/workflow",
    "crates/testing/test-programs/types/activity",
    "crates/testing/test-programs/types/workflow",
    "crates/testing/tests",
    "crates/val-json",
]

[workspace.package]
version = "0.1.0"
authors = ["Project Developers"]
edition = "2021"
rust-version = "1.73.0"

[workspace.dependencies]
runtime.path = "crates/runtime"
test-programs-builder.path = "crates/testing/test-programs-builder"
val-json.path = "crates/val-json"

anyhow = { version = "1.0", features = ["backtrace"] }
async-trait = "0.1"
cargo_metadata = "0.18"
cargo-component-bindings = "0.5"
criterion = "0.5"
indexmap = "2.1"
itertools = "0.12"
lazy_static = "1.4"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
thiserror = "1.0"
tokio = { version = "1.34" }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
wasmtime = { version = "15.0", features = ["component-model"] }
wasmtime-wasi = "15.0"
wasmtime-wasi-http = "15.0"
wiremock = "0.5"
wit-component = "0.18"
wit-parser = "0.13"
