[workspace]
resolver = "2"
members = [
    "crates/runtime",
    "crates/workflows/hello-world",
    "crates/activities/wasm-email-provider",

    "wasmtime/cranelift",
    "wasmtime/cranelift/isle/fuzz",
    "wasmtime/cranelift/isle/islec",
    "wasmtime/cranelift/serde",
    "wasmtime/crates/bench-api",
    "wasmtime/crates/c-api",
    "wasmtime/crates/cli-flags",
    "wasmtime/crates/environ/fuzz",
    "wasmtime/crates/jit-icache-coherence",
    "wasmtime/crates/test-programs/wasi-tests",
    "wasmtime/crates/test-programs/wasi-http-tests",
    "wasmtime/crates/test-programs/wasi-http-proxy-tests",
    "wasmtime/crates/test-programs/wasi-sockets-tests",
    "wasmtime/crates/test-programs/command-tests",
    "wasmtime/crates/test-programs/reactor-tests",
    "wasmtime/crates/wmemcheck",
    "wasmtime/crates/wasi-preview1-component-adapter",
    "wasmtime/crates/wasi-preview1-component-adapter/verify",
    "wasmtime/crates/winch",
    "wasmtime/examples/fib-debug/wasm",
    "wasmtime/examples/wasi/wasm",
    "wasmtime/examples/tokio/wasm",
    "wasmtime/fuzz",
    "wasmtime/winch",
    "wasmtime/winch/codegen",
]

[workspace.package]
version = "14.0.4"
authors = ["The Wasmtime Project Developers"]
edition = "2021"
# Wasmtime's current policy is that this number can be no larger than the
# current stable release of Rust minus 2.
rust-version = "1.70.0"


[workspace.dependencies]
wasmtime-wmemcheck = { path = "wasmtime/crates/wmemcheck", version = "=14.0.4" }
wasmtime = { path = "wasmtime/crates/wasmtime", version = "14.0.4", default-features = false }
wasmtime-cache = { path = "wasmtime/crates/cache", version = "=14.0.4" }
wasmtime-cli-flags = { path = "wasmtime/crates/cli-flags", version = "=14.0.4" }
wasmtime-cranelift = { path = "wasmtime/crates/cranelift", version = "=14.0.4" }
wasmtime-cranelift-shared = { path = "wasmtime/crates/cranelift-shared", version = "=14.0.4" }
wasmtime-winch = { path = "wasmtime/crates/winch", version = "=14.0.4" }
wasmtime-environ = { path = "wasmtime/crates/environ", version = "=14.0.4" }
wasmtime-explorer = { path = "wasmtime/crates/explorer", version = "=14.0.4" }
wasmtime-fiber = { path = "wasmtime/crates/fiber", version = "=14.0.4" }
wasmtime-types = { path = "wasmtime/crates/types", version = "14.0.4" }
wasmtime-jit = { path = "wasmtime/crates/jit", version = "=14.0.4" }
wasmtime-jit-debug = { path = "wasmtime/crates/jit-debug", version = "=14.0.4" }
wasmtime-runtime = { path = "wasmtime/crates/runtime", version = "=14.0.4" }
wasmtime-wast = { path = "wasmtime/crates/wast", version = "=14.0.4" }
wasmtime-wasi = { path = "wasmtime/crates/wasi", version = "14.0.4", default-features = false }
wasmtime-wasi-http = { path = "wasmtime/crates/wasi-http", version = "=14.0.4", default-features = false }
wasmtime-wasi-nn = { path = "wasmtime/crates/wasi-nn", version = "14.0.4" }
wasmtime-wasi-threads = { path = "wasmtime/crates/wasi-threads", version = "14.0.4" }
wasmtime-component-util = { path = "wasmtime/crates/component-util", version = "=14.0.4" }
wasmtime-component-macro = { path = "wasmtime/crates/component-macro", version = "=14.0.4" }
wasmtime-asm-macros = { path = "wasmtime/crates/asm-macros", version = "=14.0.4" }
wasmtime-versioned-export-macros = { path = "wasmtime/crates/versioned-export-macros", version = "=14.0.4" }
component-test-util = { path = "wasmtime/crates/misc/component-test-util" }
component-fuzz-util = { path = "wasmtime/crates/misc/component-fuzz-util" }
wiggle = { path = "wasmtime/crates/wiggle", version = "=14.0.4", default-features = false }
wiggle-macro = { path = "wasmtime/crates/wiggle/macro", version = "=14.0.4" }
wiggle-generate = { path = "wasmtime/crates/wiggle/generate", version = "=14.0.4" }
wasi-common = { path = "wasmtime/crates/wasi-common", version = "=14.0.4" }
wasi-tokio = { path = "wasmtime/crates/wasi-common/tokio", version = "=14.0.4" }
wasi-cap-std-sync = { path = "wasmtime/crates/wasi-common/cap-std-sync", version = "=14.0.4" }
wasmtime-fuzzing = { path = "wasmtime/crates/fuzzing" }
wasmtime-jit-icache-coherence = { path = "wasmtime/crates/jit-icache-coherence", version = "=14.0.4" }
wasmtime-wit-bindgen = { path = "wasmtime/crates/wit-bindgen", version = "=14.0.4" }

cranelift-wasm = { path = "wasmtime/cranelift/wasm", version = "0.101.4" }
cranelift-codegen = { path = "wasmtime/cranelift/codegen", version = "0.101.4", default-features = false, features = [
    "std",
    "unwind",
] }
cranelift-frontend = { path = "wasmtime/cranelift/frontend", version = "0.101.4" }
cranelift-entity = { path = "wasmtime/cranelift/entity", version = "0.101.4" }
cranelift-native = { path = "wasmtime/cranelift/native", version = "0.101.4" }
cranelift-module = { path = "wasmtime/cranelift/module", version = "0.101.4" }
cranelift-interpreter = { path = "wasmtime/cranelift/interpreter", version = "0.101.4" }
cranelift-reader = { path = "wasmtime/cranelift/reader", version = "0.101.4" }
cranelift-filetests = { path = "wasmtime/cranelift/filetests" }
cranelift-object = { path = "wasmtime/cranelift/object", version = "0.101.4" }
cranelift-jit = { path = "wasmtime/cranelift/jit", version = "0.101.4" }
cranelift-fuzzgen = { path = "wasmtime/cranelift/fuzzgen" }
cranelift-bforest = { path = "wasmtime/cranelift/bforest", version = "0.101.4" }
cranelift-control = { path = "wasmtime/cranelift/control", version = "0.101.4" }
cranelift = { path = "wasmtime/cranelift/umbrella", version = "0.101.4" }

winch-codegen = { path = "wasmtime/winch/codegen", version = "=0.12.4" }
winch-filetests = { path = "wasmtime/winch/filetests" }
winch-test-macros = { path = "wasmtime/winch/test-macros" }

wasi-preview1-component-adapter = { path = "wasmtime/crates/wasi-preview1-component-adapter" }
byte-array-literals = { path = "wasmtime/crates/wasi-preview1-component-adapter/byte-array-literals" }

# Bytecode Alliance maintained dependencies:
# ---------------------------
regalloc2 = "0.9.2"

# cap-std family:
target-lexicon = { version = "0.12.3", default-features = false, features = [
    "std",
] }
cap-std = "2.0.0"
cap-rand = { version = "2.0.0", features = ["small_rng"] }
cap-fs-ext = "2.0.0"
cap-net-ext = "2.0.0"
cap-time-ext = "2.0.0"
cap-tempfile = "2.0.0"
fs-set-times = "0.20.0"
system-interface = { version = "0.26.0", features = ["cap_std_impls"] }
io-lifetimes = { version = "2.0.2", default-features = false }
io-extras = "0.18.0"
rustix = "0.38.8"
is-terminal = "0.4.0"
# wit-bindgen:
wit-bindgen = { version = "0.13.0", default-features = false }

# wasm-tools family:
wasmparser = "0.115.0"
wat = "1.0.77"
wast = "66.0.2"
wasmprinter = "0.2.70"
wasm-encoder = "0.35.0"
wasm-smith = "0.12.21"
wasm-mutate = "0.2.38"
wit-parser = "0.12.1"
wit-component = "0.16.0"

# Non-Bytecode Alliance maintained dependencies:
# --------------------------
object = { version = "0.32", default-features = false, features = [
    'read_core',
    'elf',
    'std',
] }
gimli = { version = "0.28.0", default-features = false, features = [
    'read',
    'std',
] }
anyhow = "1.0.22"
windows-sys = "0.48.0"
env_logger = "0.10"
log = { version = "0.4.8", default-features = false }
clap = { version = "4.3.12", features = ["color", "suggestions", "derive"] }
hashbrown = { version = "0.14", default-features = false }
capstone = "0.9.0"
once_cell = "1.12.0"
smallvec = { version = "1.6.1", features = ["union"] }
tracing = "0.1.26"
bitflags = "2.0"
thiserror = "1.0.43"
async-trait = "0.1.71"
heck = "0.4"
similar = "2.1.0"
toml = "0.5.9"
# serde and serde_derive must have the same version
serde = "1.0.188"
serde_derive = "1.0.188"
serde_json = "1.0.80"
glob = "0.3.0"
libfuzzer-sys = "0.4.0"
walkdir = "2.3.3"
cfg-if = "1.0"
tempfile = "3.1.0"
filecheck = "0.5.0"
libc = "0.2.60"
file-per-thread-logger = "0.2.0"
tokio = { version = "1.26.0", features = ["rt", "time"] }
hyper = "=1.0.0-rc.3"
http = "0.2.9"
http-body = "=1.0.0-rc.2"
http-body-util = "=0.1.0-rc.2"
bytes = "1.4"
futures = { version = "0.3.27", default-features = false }
indexmap = "2.0.0"
pretty_env_logger = "0.5.0"
syn = "2.0.25"
test-log = { version = "0.2", default-features = false, features = ["trace"] }
tracing-subscriber = { version = "0.3.1", default-features = false, features = [
    'fmt',
    'env-filter',
] }
url = "2.3.1"
humantime = "2.0.0"
