[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = { version = "14.0", features = [
    "component-model",
], path = "../../wasmtime/crates/wasmtime" }
anyhow = { version = "1.0.75", features = ["backtrace"] }
async-trait = "0.1"
thiserror = "1.0"
tokio = { version = "1.34", features = ["full"] }
wasmtime-wasi-http = { workspace = true }
wasmtime-wasi = { workspace = true }
wit-component = "0.18.2"
wit-parser = "0.13.0"
lazy_static = "1.4.0"
