[package]
name = "test_programs_http_get_workflow"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
cargo-component-bindings = { workspace = true }

[lib]
crate-type = ["cdylib"]

[features]
wasm = []
default = ["wasm"]

[package.metadata.component.dependencies]

[package.metadata.component.target.dependencies]
"testing:http" = { path = "../wit" }
