[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.74"
tokio = { version = "1.34", features = ["full"] }
wasmtime = { version = "14.0", features = ["component-model"] }
