[package]
name = "test_programs_http_get_activity_builder"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[build-dependencies]
cargo_metadata.workspace = true
