[package]
name = "test_programs_types_activity_builder"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[build-dependencies]
test_programs_util.workspace = true
