[package]
name = "test-programs-sleep-workflow"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
cargo-component-bindings = { workspace = true }

[lib]
crate-type = ["cdylib"]

[features]
wasm = []
default = ["wasm"]

[package.metadata.component.dependencies]

[package.metadata.component.target.dependencies]
"my-org:workflow-engine".path = "../../../../../wit/workflow-engine/"
