[package]
name = "test_programs_fibo_activity"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
cargo-component-bindings.workspace = true

[lib]
crate-type = ["cdylib"]

[package.metadata.component.dependencies]

[package.metadata.component.target.dependencies]
"testing:fibo" = { path = "../wit" }
