[package]
name = "test-programs-sleep-activity"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
wit-bindgen-rt.workspace = true

[lib]
crate-type = ["cdylib"]

[features]
wasm = []

[package.metadata.component.dependencies]

[package.metadata.component.target.dependencies]
"testing:sleep".path = "../wit"
"wasi:cli".path = "wit/deps/cli"
