[package]
name = "test-programs-sleep-activity"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
cargo-component-bindings.workspace = true

[lib]
crate-type = ["cdylib"]

[features]
wasm = []
default = ["wasm"]

[package.metadata.component.dependencies]

[package.metadata.component.target.dependencies]
"testing:sleep".path = "../wit"
"wasi:cli".path = "wit/deps/cli"
