[package]
name = "utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
concepts.workspace = true
val-json.workspace = true

cfg-if.workspace = true
chrono.workspace = true
derivative.workspace = true
hashbrown.workspace = true
hyper.workspace = true
indexmap.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
wasmtime-wasi-http.workspace = true
wasmtime-wasi.workspace = true
wasmtime.workspace = true
wit-parser.workspace = true

[dev-dependencies]
insta.workspace = true
madsim.workspace = true
rstest.workspace = true
test-programs-fibo-workflow-builder.workspace = true
test-programs-http-get-workflow-builder.workspace = true
test-utils.workspace = true
tokio.workspace = true

[lints]
workspace = true
