[package]
name = "executor"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
concepts.workspace = true
utils.workspace = true
val-json.workspace = true

arbitrary.workspace = true
assert_matches.workspace = true
async-channel.workspace = true
async-trait.workspace = true
cfg-if.workspace = true
chrono.workspace = true
derivative.workspace = true
derive_more.workspace = true
indexmap.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
ulid.workspace = true
valuable.workspace = true

[dev-dependencies]
db-mem.workspace = true
db-sqlite.workspace = true
test-utils.workspace = true

anyhow.workspace = true
madsim.workspace = true

[features]
test = []

[lints]
workspace = true
