[package]
name = "test_programs_fibo_workflow_builder"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[build-dependencies]
test_programs_util.workspace = true
