[package]
name = "test-utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
arbitrary.workspace = true
chrono.workspace = true
madsim.workspace = true
tracing.workspace = true
tracing-chrome.workspace = true
tracing-subscriber.workspace = true
utils.workspace = true

[lints]
workspace = true
