[package]
name = "http-get-workflow"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo-component-bindings = { workspace = true }

[lib]
crate-type = ["cdylib"]

[package.metadata.component.dependencies]

[package.metadata.component.target.dependencies]
"component:wasm-email-provider" = { path = "../http-get-wit" }

