[package]
name = "test-programs-types-workflow-builder"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[build-dependencies]
cargo-component-builder.workspace = true
