[package]
name = "wasm-workers"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
concepts.workspace = true
db.workspace = true
executor.workspace = true
utils.workspace = true
val-json.workspace = true

arbitrary.workspace = true
assert_matches.workspace = true
async-channel.workspace = true
async-trait.workspace = true
cfg-if.workspace = true
chrono = { workspace = true, features = ["arbitrary"] }
derive_more.workspace = true
indexmap.workspace = true
rand.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync", "rt", "time", "macros"] }
tracing.workspace = true
ulid.workspace = true
valuable.workspace = true
wasmtime-wasi-http.workspace = true
wasmtime-wasi.workspace = true
wasmtime.workspace = true

[dev-dependencies]
test-programs-fibo-activity-builder.workspace = true
test-programs-fibo-workflow-builder.workspace = true
test-programs-sleep-activity-builder.workspace = true
test-programs-sleep-workflow-builder.workspace = true
test-utils.workspace = true

async-trait.workspace = true
futures-util.workspace = true
madsim.workspace = true
rstest.workspace = true

[lints]
workspace = true
