[package]
name = "test-programs-fibo-workflow"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
wit-bindgen-rt.workspace = true

[lib]
crate-type = ["cdylib"]

[features]
wasm = []

[package.metadata.component.dependencies]

[package.metadata.component.target.dependencies]
"testing:fibo" = { path = "../wit" }
"testing:fibo-obelisk-ext" = { path = "../wit-obelisk-ext" }
"obelisk:workflow".path = "../../../../wasm-workers/host-wit/"
