name: Install Dependencies

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/cache-cargo-install-action@v1
        with:
          tool: cargo-component@0.10.1
