name: test-nosim
permissions:
  contents: read
# This configuration allows maintainers of this repo to create a branch and pull request based on
# the new branch. Restricting the push trigger to the main branch ensures that the PR only gets
# built once.
on:
  push:
    branches:
      - main
  pull_request:
# If new code is pushed to a PR branch, then cancel in progress workflows for that PR.

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  test-nosim:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"
      - name: Load nix store
        run: nix develop --command echo
      - name: cargo test (nosim)
        run: nix develop --command cargo nextest run --profile ci --no-capture --filter-expr '!test(/perf/)'
        env:
          RUSTFLAGS: "--cfg tokio_unstable --cfg tracing_unstable"
          RUST_LOG: "info,executor=trace,wasm_workers=trace,db=info"
  test-madsim:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"
      - name: Load nix store
        run: nix develop --command echo
      - name: cargo test (madsim)
        run: nix develop --command cargo nextest run --profile ci --no-capture --filter-expr '!test(/perf/)'
        env:
          RUSTFLAGS: "--cfg madsim --cfg tokio_unstable --cfg tracing_unstable"
          RUST_LOG: "info,executor=trace,wasm_workers=trace,db=info"
